<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ы</title>
    <link rel="stylesheet" type="text/css" href="/css/style.x86950.css"/>
</head>
<body>
<div>
    <h1>Employees</h1>
</div>

<#--<form action="/add" method="post">-->
<#--    <label>-->
<#--        <input type="text" name="Name" placeholder="Name">-->
<#--        <input type="text" name="Department" placeholder="Department">-->
<#--        <input type="text" name="Post" placeholder="Post">-->
<#--        <input type="text" name="Contact" placeholder="Contact">-->
<#--        <input type="date" name="DateEmployment" placeholder="Date of employment" >-->
<#--    </label>-->
<#--    <button>Add</button>-->
<#--</form>-->
<#--<br>-->
<#--<table>-->
<#--    <tr>-->
<#--        <td>Id</td>-->
<#--        <td>Name</td>-->
<#--        <td>Department</td>-->
<#--        <td>Post</td>-->
<#--        <td>Contact</td>-->
<#--        <td>Date of employment</td>-->
<#--    </tr>-->
<#--    <#list employeeList as employee>-->
<#--        <tr>-->
<#--            <td>${employee.id}</td>-->
<#--            <td>${employee.name}</td>-->
<#--            <td>${employee.department}</td>-->
<#--            <td>${employee.post}</td>-->
<#--            <td>${employee.contact}</td>-->
<#--            <td>${employee.dateEmployment}</td>-->
<#--            <td><a href="${'/delete/'+employee.id}">Delete</a></td>-->
<#--        </tr>-->
<#--    </#list>-->
</body>
</html>